### ISSUE TITLE
ignore/merge partitions types

### ISSUE THREAD

**Issue by Awalgawe** [kristiandupont/kanel#183] opened 2021-07-12 07:20 UTC
Hello,
Partitions duplicates the same types.
In my case I have  close to 1000 extra files : /

**Comment by kristiandupont** [comment] 2021-07-13 06:40
Hm ok I haven't encountered this because I am not yet partitioning. Would it be possible for you to show me how to reproduce this error in a somewhat simple way?

**Comment by Awalgawe** [comment] 2021-07-14 11:22
yes: 
```sql
CREATE SCHEMA test
  CREATE TABLE test (
    id SERIAL,
    type TEXT NOT NULL,
    PRIMARY KEY(id, type)
  ) PARTITION BY LIST(type)

  CREATE TABLE test_a PARTITION OF test FOR VALUES IN ('a')
;
```

**Comment by kristiandupont** [comment] 2021-08-29 13:41
Just to update you, I have a failing test and a half-solution for this in [extract-pg-schema](https://github.com/kristiandupont/extract-pg-schema/), but I don't think it quite works yet. I just had a baby boy so I haven't had time for these extra-curricular activities but I do think this should be easy enough to fix that I will be able to some time.

**Comment by Awalgawe** [comment] 2021-08-30 15:20
Congratulations ! ^^
Np, baby boy is a first priority ! :)
I can't see any PR about that, I can try to help if you want.

**Comment by jknight** [comment] 2022-02-10 23:40
@Awalgawe se how this looks to you:
https://github.com/kristiandupont/extract-pg-schema/pull/158

**Comment by Awalgawe** [comment] 2022-02-11 10:35
@jknight Just tested (not an a real project), it seems to work ! :+1:

**Comment by jknight** [comment] 2022-02-11 10:45
@Awalgawe - @kristiandupont  merged this into `extract-pg-schema` so it should work in out of the box in Kanal now:
https://github.com/kristiandupont/extract-pg-schema/releases/tag/v3.1.4

**Comment by kristiandupont** [comment] 2022-02-11 10:50
I published a new release, so you should be able to update Kanel now. Thanks!

**Closed by kristiandupont** 2022-02-11 10:50 UTC
